### ISSUE TITLE
relinquish "sails-mssql" npm name

### ISSUE THREAD

**Issue by tjwebb** [sergeibelov/sails-mssql#3]
Please relinquish ownership of the "sails-mssql" npm module name. You don't seem to be maintaining this project, and I'd like to publish updated versions of this module.

**Comment by tjwebb** [comment]
I'll file a case with npm. Thanks.

**Comment by sergeibelov** [comment]
Travis,

Sorry for ignoring your request, I just found it. I can't find anything on
NPM that would allow me to relinquish the name.

What can I do to make this happen?

Serge
